/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ex.Panels;

import com.ex.Models.*;
import java.util.List;
import java.util.ArrayList;
import com.ex.Utilities.CusDetailPanelSQLHelper;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author cn200
 */
public class CusDetailPanel extends javax.swing.JPanel {

    private com.ex.Dialogs.CusDetailDialog parent;
    private Prescription pres;
    private Customer cus;
    private DefaultTableModel tm;
    private CusDetailPanelSQLHelper helper = new CusDetailPanelSQLHelper();
    
    private List<Prescription> list = new ArrayList<>();
    
    /**
     * Creates new form CusDetailPanel
     */
    public CusDetailPanel(com.ex.Dialogs.CusDetailDialog parent, Customer cus) {
        initComponents();
        this.parent = parent;
        this.cus = cus;
        
        // Bảng 
        String[] cols = {"Mã đơn", "Thời gian"};
        tm = new DefaultTableModel(cols, 0);
        tb.setModel(tm);
        tb.getColumnModel().getColumn(0).setPreferredWidth(40);
//        tb.getColumnModel().getColumn(1).setPreferredWidth(80);
//        tb.getColumnModel().getColumn(2).setPreferredWidth(80);
//        tb.getColumnModel().getColumn(3).setPreferredWidth(80);
//        tb.getColumnModel().getColumn(4).setPreferredWidth(80);
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        // Khởi tạo thông tin 
        init();
    }
    
    private void init() {
        // Thông tin cơ bản
        lblName.setText(cus.getName());
        lblBirthday.setText(cus.getsBirthday());
        lblAddress.setText(cus.getAddress());
        lblPhoneNumber.setText(cus.getPhoneNumber());
        
        // Bảng 
        list = helper.searchPres(cus);
        for (int i = 0; i < list.size(); ++i) {
            tm.addRow(new Object[] {"M" + list.get(i).getKey(), list.get(i).getsTime(true, true)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();

        jLabel5.setText("Số điện thoại:");

        jLabel1.setText("Họ và tên:");

        lblName.setText("name");

        jLabel3.setText("Ngày sinh:");

        lblBirthday.setText("birthday");

        jLabel2.setText("Địa chỉ:");

        lblAddress.setText("address");

        lblPhoneNumber.setText("phone number");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        btnDetail.setText("Xem chi tiết");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBirthday))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAddress)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDetail)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName)
                    .addComponent(lblPhoneNumber)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBirthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetail)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        int row = tb.getSelectedRow();
        
        if (row >= 0 && row < list.size()) {
            parent.open(list.get(row).getId());
        }
    }//GEN-LAST:event_btnDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
