/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ex.Panels;

import java.util.List;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.event.*;

import com.ex.Dialogs.ResultSearchCustomerDialog;
import com.ex.Models.Customer;

/**
 *
 * @author cn200
 */
public class ResultSearchCustomerPanel extends javax.swing.JPanel {

    private DefaultTableModel tm;
    private ResultSearchCustomerDialog parent;
    private List<Customer> list;
    
    private int ver = 0;
    
    /**
     * Creates new form ResultSearchCustomerPanel
     */
    public ResultSearchCustomerPanel(ResultSearchCustomerDialog parent, List<Customer> list) {
        initComponents();
        this.parent = parent;
        this.list = list;
        
        // Bảng 
        String[] cols = {"Mã", "Họ và tên", "Địa chỉ", "Ngày sinh", "Số điện thoại"};
        tm = new DefaultTableModel(cols, 0);
        tb.setModel(tm);
        tb.getColumnModel().getColumn(0).setPreferredWidth(20);
        tb.getColumnModel().getColumn(1).setPreferredWidth(180);
        tb.getColumnModel().getColumn(2).setPreferredWidth(65);
        tb.getColumnModel().getColumn(3).setPreferredWidth(50);
        tb.getColumnModel().getColumn(4).setPreferredWidth(60);
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        // Khởi tạo bảng
        init();
    }
    
    public ResultSearchCustomerPanel(ResultSearchCustomerDialog parent, List<Customer> list, int ver) {
        initComponents();
        this.parent = parent;
        this.list = list;
        this.ver = ver;
        
        // Bảng 
        String[] cols = {"Mã", "Họ và tên", "Địa chỉ", "Ngày sinh", "Số điện thoại"};
        tm = new DefaultTableModel(cols, 0);
        tb.setModel(tm);
        tb.getColumnModel().getColumn(0).setPreferredWidth(20);
        tb.getColumnModel().getColumn(1).setPreferredWidth(180);
        tb.getColumnModel().getColumn(2).setPreferredWidth(65);
        tb.getColumnModel().getColumn(3).setPreferredWidth(50);
        tb.getColumnModel().getColumn(4).setPreferredWidth(60);
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        // Khởi tạo bảng
        init();
    }
    
    private void init() {
        for (int i = 0; i < list.size(); ++i) {
            tm.addRow(list.get(i).toObject());
        }
    }
    
    private void confirmAction() {
        int row = tb.getSelectedRow();
        
        if (row >= 0 && row < list.size()) {
            if (ver == 0) {
                parent.close(list.get(row).getId());
            } else {
                parent.close(list.get(row).getId(), ver);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ và tên", "Địa chỉ", "Ngày sinh", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(1).setMinWidth(150);
        }

        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirm))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        confirmAction();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void tbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmAction();
        }
    }//GEN-LAST:event_tbKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
